package git4idea.mpsbl.stubs.usage.actions.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class MyGroup_ActionGroup extends GeneratedActionGroup {
  private static Logger LOG = LogManager.getLogger(MyGroup_ActionGroup.class);
  public static final String ID = "git4idea.mpsbl.stubs.usage.actions.plugin.MyGroup_ActionGroup";
  public MyGroup_ActionGroup() {
    super("MyGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    try {
      MyGroup_ActionGroup.this.addAction("git4idea.mpsbl.stubs.usage.actions.plugin.TestAction_Action");
    } catch (Throwable t) {
      LOG.error("User group error", t);
    }
  }
}
